### ISSUE TITLE
Bug: .yfm config file is ignored by docs translation

### ISSUE THREAD

**Issue by shiftuya** [diplodoc-platform/cli#550]
According to https://ydocs.tech/en/tools/docs/translate, setup for docs translation requires `yandexCloudTranslateFolderId` to be set in the .yfm config.

To reproduce:
- Set `YANDEX_OAUTH_TOKEN` environment variable with a valid OAuth token
- Set `yandexCloudTranslateFolderId` inside the .yfm config file
- Run translation with `yfm translate --input input_folder --output output_folder --source-language ru --target-language en`

Expected behavior: .yfm file contents are read and used for translation

Actual behavior: apparently, .yfm file contents are ignored, yfm translate fails with following message:
```
ClientError: /yandex.cloud.ai.translate.v2.TranslationService/Translate UNAUTHENTICATED: You have to specify folder ID for user account
```

**Comment by 3y3** [comment]
Fixed in 4.14
