### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by sofit** [diplodoc-platform/cli#565]
Выполняю команду 
> npm i @diplodoc/cli -g
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@diplodoc%2fcli - Not found
npm ERR! 404
npm ERR! 404  '@diplodoc/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by sofit** [comment]
видимо нужно ставить npm i @doc-tools/docs -g

**Comment by moki** [comment]
@sofit sorry for the late response, builder cli

https://www.npmjs.com/package/@diplodoc/cli

**Comment by sofit** [comment]
I want to build HTML pages from *.md files using diplodoc. Documentation says use @doc-tools/docs (https://diplodoc.com/docs/ru/tools/docs/). In this project i see @diplodoc/cli
What is the difference?

**Comment by moki** [comment]
> I want to build HTML pages from *.md files using diplodoc. Documentation says use @doc-tools/docs (https://diplodoc.com/docs/ru/tools/docs/). In this project i see @diplodoc/cli What is the difference?

sorry it is typo in the documentation

please use `@diplodoc/cli` package
