### ISSUE TITLE
Missing line breaks in code block in v4.8.0

### ISSUE THREAD

**Issue by maratori** [diplodoc-platform/cli#631]
The latest version `v4.8.0` introduced a bug. There are no line breaks in code blocks.

Here is a simple example of how to reproduce the issue.

1. Create `bug.sh` with the following content:

````shell
#!/bin/bash
mkdir -p src
echo 'href: index.md' > src/toc.yaml
cat << "EOF" > src/index.md
```
line 1
line 2
```
EOF
npm i @diplodoc/cli@v4.7.0 -g
yfm -i src -o v4.7.0
npm i @diplodoc/cli@v4.8.0 -g
yfm -i src -o v4.8.0
diff v4.7.0/index.html v4.8.0/index.html
````

2. Run it in docker:

```shell
docker run --rm -v "`pwd`:/app" -w "/app" node ./bug.sh
```

The diff from `bug.sh` shows the following.
- v4.7.0:
  ```html
  <pre><code class=\"hljs\">line 1\nline 2\n</code></pre>
  ```
- v4.8.0:
  ```html
  <pre><code class=\"hljs\">line 1line 2</code></pre>
  ```

**Comment by 3y3** [comment]
Fixed in last versions. Check it please.

**Comment by maratori** [comment]
I confirm the bug is not reproduced at v4.13.3
