### ISSUE TITLE
В режиме генерации в статику не работает установка языка для текстов настроек

### ISSUE THREAD

**Issue by goshander** [diplodoc-platform/cli#640]
В файле `.yfm` указан язык `lang: ru`, но для настроек и системных элементов он не применяется

![image](https://github.com/diplodoc-platform/cli/assets/5037509/f94d708d-51e5-4244-a71b-45e3a95cd5b3)

**Comment by sofit** [comment]
такая же проблема в #636

**Comment by serg-vostrikov** [comment]
аналогичная проблема

**Comment by martyanovandrey** [comment]
исправлено в версии 4.21.0 

https://github.com/diplodoc-platform/client/pull/40
